### ISSUE TITLE
Question about data split

### ISSUE THREAD

**Issue by cviviers** [kilgore92/GeneralizedProbabilisticUNet#1]
Hi Ishaan,
Very interesting work and result.
I was wondering if you had split the data into train/val/test on a per patient level? It was not clear to me from your paper.

Thanks in advance for the feedback.

**Comment by ishaanb92** [comment]
Hi Christiaan,

Thanks for your interest! Apologies for the delay in the reply, I was away.

I used a pre-processed version of the LIDC-IDRI dataset available at https://drive.google.com/drive/folders/1xKfKCQo8qa6SAr3u7qWNtQjIphIrvmd5

To answer your question, I've added the script I used to split the dataset under the 'data' folder. Hope that helps, and let me know if you have further questions.

Cheers,
Ishaan
