### ISSUE TITLE
Train my own model

### ISSUE THREAD

**Issue by ZhouCX117** [kilgore92/GeneralizedProbabilisticUNet#2]
Hi, thanks for your excellent work. I can't find any train files. Could you please give me a guide on how to train by myself?

**Comment by ishaanb92** [comment]
Hi Zhou,

Thanks! Apologies for not having the entire repository ready, I am in the process of making a journal submission, so a lot of the training/analysis scripts are undergoing changes. If you want to train the model, I suggest downloading the LIDC-IDRI data from https://github.com/stefanknegt/Probabilistic-Unet-Pytorch and writing a simple training script. I did not use any data augmentation and I have provided the code to split the data into train/validation/test in the 'data' folder. Hope this helps, and I'll be uploading the rest of the files soon! Thanks once again for your interest.

For additional information, you may refer to Section 4.2 and Appendix A (Table 3) in our paper: https://arxiv.org/abs/2207.12872

Cheers,
Ishaan
